name: FishOnlyFish
version: 1.0
main: com.axevillager.fishonlyfish.Main
author: Axe_Villager
website: https://github.com/AxeVillager/Minecraft-Plugin-FishOnlyFish
description: Makes you only able to fish fish.
